# Generated by Django 4.1.5 on 2023-02-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
