# Generated by Django 4.1.5 on 2023-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0005_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
