# Generated by Django 4.1.5 on 2023-02-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0006_alter_message_message_alter_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
